# Generated by Django 5.1 on 2024-09-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_farmer_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20)),
                ('ph_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_stamp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tds', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
