# Generated by Django 5.1 on 2024-09-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ph',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
