# Generated by Django 5.1 on 2024-09-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ph_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ph',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
